// Code generated by MockGen. DO NOT EDIT.
// Source: borrowers.go
//
// Generated by this command:
//
//	mockgen -source borrowers.go -destination mocks/borrowers.go --package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dbmodels "github.com/csokviktor/lib_manager/internal/repository/dbmodels"
	gomock "go.uber.org/mock/gomock"
)

// MockBorrowers is a mock of Borrowers interface.
type MockBorrowers struct {
	ctrl     *gomock.Controller
	recorder *MockBorrowersMockRecorder
	isgomock struct{}
}

// MockBorrowersMockRecorder is the mock recorder for MockBorrowers.
type MockBorrowersMockRecorder struct {
	mock *MockBorrowers
}

// NewMockBorrowers creates a new mock instance.
func NewMockBorrowers(ctrl *gomock.Controller) *MockBorrowers {
	mock := &MockBorrowers{ctrl: ctrl}
	mock.recorder = &MockBorrowersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBorrowers) EXPECT() *MockBorrowersMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBorrowers) Create(ctx context.Context, newBorrower *dbmodels.Borrower) (*dbmodels.Borrower, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, newBorrower)
	ret0, _ := ret[0].(*dbmodels.Borrower)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockBorrowersMockRecorder) Create(ctx, newBorrower any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBorrowers)(nil).Create), ctx, newBorrower)
}

// GetAll mocks base method.
func (m *MockBorrowers) GetAll(ctx context.Context) ([]dbmodels.Borrower, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]dbmodels.Borrower)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockBorrowersMockRecorder) GetAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockBorrowers)(nil).GetAll), ctx)
}

// GetByID mocks base method.
func (m *MockBorrowers) GetByID(ctx context.Context, id string) (*dbmodels.Borrower, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*dbmodels.Borrower)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockBorrowersMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockBorrowers)(nil).GetByID), ctx, id)
}
