// Code generated by MockGen. DO NOT EDIT.
// Source: authors.go
//
// Generated by this command:
//
//	mockgen -source authors.go -destination mocks/authors.go --package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dbmodels "github.com/csokviktor/qwbSfwVEyB/manager/internal/repository/dbmodels"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthors is a mock of Authors interface.
type MockAuthors struct {
	ctrl     *gomock.Controller
	recorder *MockAuthorsMockRecorder
	isgomock struct{}
}

// MockAuthorsMockRecorder is the mock recorder for MockAuthors.
type MockAuthorsMockRecorder struct {
	mock *MockAuthors
}

// NewMockAuthors creates a new mock instance.
func NewMockAuthors(ctrl *gomock.Controller) *MockAuthors {
	mock := &MockAuthors{ctrl: ctrl}
	mock.recorder = &MockAuthorsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthors) EXPECT() *MockAuthorsMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAuthors) Create(arg0 context.Context, arg1 *dbmodels.Author) (*dbmodels.Author, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*dbmodels.Author)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAuthorsMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAuthors)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockAuthors) Delete(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAuthorsMockRecorder) Delete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAuthors)(nil).Delete), arg0, arg1)
}

// GetAll mocks base method.
func (m *MockAuthors) GetAll(arg0 context.Context) ([]dbmodels.Author, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", arg0)
	ret0, _ := ret[0].([]dbmodels.Author)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockAuthorsMockRecorder) GetAll(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockAuthors)(nil).GetAll), arg0)
}

// GetByID mocks base method.
func (m *MockAuthors) GetByID(arg0 context.Context, arg1 string) (*dbmodels.Author, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", arg0, arg1)
	ret0, _ := ret[0].(*dbmodels.Author)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAuthorsMockRecorder) GetByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAuthors)(nil).GetByID), arg0, arg1)
}

// Update mocks base method.
func (m *MockAuthors) Update(arg0 context.Context, arg1 *dbmodels.Author) (*dbmodels.Author, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(*dbmodels.Author)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockAuthorsMockRecorder) Update(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAuthors)(nil).Update), arg0, arg1)
}
